"""add submit_started_at

Revision ID: 07b5ff5f5bd7
Revises: 3d0c52a2fcc9
Create Date: 2026-09-30 19:09:05.081722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b5ff5f5bd7'
down_revision: Union[str, Sequence[str], None] = '3d0c52a2fcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('submit_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'submit_started_at')
    # ### end Alembic commands ###
