"""drop unused progress_percent

Revision ID: 0d9221aec015
Revises: 34570e71da1e
Create Date: 2026-10-01 23:43:01.585606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9221aec015'
down_revision: Union[str, Sequence[str], None] = '34570e71da1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'progress_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('progress_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
