"""add owner_id

Revision ID: 2d02df150d72
Revises: 4e5405c5965a
Create Date: 2026-09-30 22:22:39.400761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d02df150d72'
down_revision: Union[str, Sequence[str], None] = '4e5405c5965a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('owner_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audio_jobs_owner_id'), 'audio_jobs', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_jobs_owner_id'), table_name='audio_jobs')
    op.drop_column('audio_jobs', 'owner_id')
    # ### end Alembic commands ###
