"""add audio_deleted_at

Revision ID: 34570e71da1e
Revises: 2d02df150d72
Create Date: 2026-10-01 22:03:22.648282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34570e71da1e'
down_revision: Union[str, Sequence[str], None] = '2d02df150d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'audio_deleted_at')
    # ### end Alembic commands ###
