"""create audio_jobs

Revision ID: 3d0c52a2fcc9
Revises: 
Create Date: 2026-09-30 17:21:15.581503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0c52a2fcc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('language_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'UPLOADED', 'QUEUED', 'TRANSCRIBING', 'SUMMARIZING', 'COMPLETED', 'FAILED', name='job_status', native_enum=False, length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('gnani_job_id', sa.String(length=64), nullable=True),
    sa.Column('gnani_status', sa.String(length=32), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UPLOADING', 'UPLOADED', 'QUEUED', 'TRANSCRIBING', 'SUMMARIZING', 'COMPLETED', 'FAILED')", name=op.f('ck_audio_jobs_job_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_jobs')),
    sa.UniqueConstraint('gnani_job_id', name=op.f('uq_audio_jobs_gnani_job_id')),
    sa.UniqueConstraint('object_key', name=op.f('uq_audio_jobs_object_key'))
    )
    op.create_index(op.f('ix_audio_jobs_created_at'), 'audio_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_created_at'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    # ### end Alembic commands ###
