"""add next_step_at

Revision ID: 4e5405c5965a
Revises: 5b891ed2e3cb
Create Date: 2026-09-30 21:47:36.103842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5405c5965a'
down_revision: Union[str, Sequence[str], None] = '5b891ed2e3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('next_step_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'next_step_at')
    # ### end Alembic commands ###
