"""add summary_partials

Revision ID: 5b891ed2e3cb
Revises: 07b5ff5f5bd7
Create Date: 2026-09-30 20:07:11.529420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b891ed2e3cb'
down_revision: Union[str, Sequence[str], None] = '07b5ff5f5bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('summary_partials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'summary_partials')
    # ### end Alembic commands ###
